### ISSUE TITLE
Thumbnails not working

### ISSUE THREAD

**Issue by mat926** [FarisHijazi/Rarbg-Enhancer-UserScript#16]
The thumbnails are not working. I tried it with different search engines and it's the same.

**Comment by FarisHijazi** [comment]
can you show post a screenshot of what you're getting

**Comment by mat926** [comment]
Here's a screenshot
![image](https://user-images.githubusercontent.com/46114199/179424716-b7014f32-9328-44b7-9465-ef732656aa2d.png)

**Comment by FarisHijazi** [comment]
That's actually weird, fyi music doesn't have thumbnails, could you hover over the links and see if you get the thumbanail poppup?

And which mirror is this? Try https://rarbgunblocked.org/index80.php

**Comment by mat926** [comment]
These are for movies not music. Hovering over the links doesn't bring the thumbnail popup.  This was on the general rargb.to site. I tried it on a mirror (rargbmirror.com) and hovering the links worked, but the thumbnail column was still empty.

**Comment by FarisHijazi** [comment]
I think i may have found the issue, expect an update soon

**Comment by FarisHijazi** [comment]
resolved in 5d81ac0f3fc30b70ceb12872e1315b840c736ca4

**Comment by mat926** [comment]
The new update still does not work.  This is the output I get from the console 
![image](https://user-images.githubusercontent.com/46114199/180670920-aaaadc3a-1c16-4400-bdb5-0e99a6ebe0d3.png)

**Comment by FarisHijazi** [comment]
Please save the entire page html and send me a link to the files. Right click - save.
And use rarbgunblocked not rarbg.to

**Comment by mat926** [comment]
I had to reset script settings to default and I was able to get it working.

**Comment by FarisHijazi** [comment]
Very strange that we got no error
